{{- if .Values.ingress.enabled }}
{{- $ingress := include "spicedb.ingress.base" . | fromYaml -}}
{{- range .Values.patches.ingress -}}
{{- $ingress = mustMergeOverwrite $ingress . -}}
{{- end -}}
{{- $ingress | toYaml -}}
{{- end }}
