{{- if and (not .Values.config.existingSecret) (ne .Values.config.datastoreEngine "memory") -}}
{{- $secretName := include "spicedb.fullname" . -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $presharedKey := "" -}}
{{- if $secret -}}
  {{- $presharedKey = index $secret.data "preshared-key" | b64dec -}}
{{- else -}}
  {{- $presharedKey = randAlphaNum 32 -}}
{{- end -}}
{{- $datastoreURI := include "spicedb.datastoreConnectionString" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
type: Opaque
data:
  preshared-key: {{ $presharedKey | b64enc | quote }}
  {{- if $datastoreURI }}
  datastore-uri: {{ $datastoreURI | b64enc | quote }}
  {{- end }}
{{- end }}
